### PR TITLE
fix: missing basic validation in route params

### LINKED ISSUE #210: Error getting RGB++ assets through assets api
```
curl --location --request GET 'https://api.testnet.rgbpp.io/rgbpp/v1/assets//' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJteS1hcHAiLCJhdWQiOiJhcGkudGVzdG5ldC5yZ2JwcC5pbyIsImp0aSI6IjlmMDZiN2Y3LTJhNjYtNGNjMy1hNzc0LTNkZWFlNTZjYzlkMSIsImlhdCI6MTcyMzU2Mzg3M30.lYhjo1LXMHJNemdlz01HKGDFKi6mD7k7iCYxcD8eJhM' \
--header 'origin: https://api.testnet.rgbpp.io' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: api.testnet.rgbpp.io' \
--header 'Connection: keep-alive'
```

- '/rgbpp/v1/assets/{btc_txid}/{vout}' Data can still be obtained even if the parameter is empty

- Response:

```
[
    {
        "cellOutput": {
            "capacity": "0x7558bdb00",
            "lock": {
                "codeHash": "0x61ca7a4796a4eb19ca4f0d065cb9b10ddcf002f10f7cbb810c706cb6bb5c3248",
                "args": "0x00000000fee38fa69efbe7ec72fb5812426181c694e872f1301ec9e2727016c8600cfa67",
                "hashType": "type"
            },
            "type": {
                "codeHash": "0x685a60219309029d01310311dba953d67029170ca4848a4ff638e57002130a0d",
                "args": "0x180abd4f1e919e3e5b407c400ce09719375c8b35001f37e8e12d564b12d53fe3",
                "hashType": "data1"
            }
        },
        "data": "0x4d000000100000001e000000290000000a000000746578742f706c61696e0700000073706f7265203420000000f6def2e6480bac681a56ee8ed0c0577f83b74b93635130632c7981fac2bb8157",
        "outPoint": {
            "txHash": "0x5b7dfbed7d03cef8ad52c627145f86f3dba7f983e43e03acd90c8687ff4011b1",
            "index": "0x0"
        },
        "blockNumber": "0xcc7aa5",
        "txIndex": "0x2",
        "typeHash": "0xb46fe1b9da5cd7cdbebbdff0e6c7930deeae1d9d60549d699789f8749f40b9f1"
    },
    {
        "cellOutput": {
            "capacity": "0x5e9f53e00",
            "lock": {
                "codeHash": "0x61ca7a4796a4eb19ca4f0d065cb9b10ddcf002f10f7cbb810c706cb6bb5c3248",
                "args": "0x00000000fe7e313c6bb99211e222dd1a4ae62a046ef4170d1e74a7252a827b0636ef6965",
                "hashType": "type"
            },
            "type": {
                "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
                "args": "0xc625c4ac0ba3ece5886d04958c3fc2d5558a21841c03577fad2d7c46e5b2b2b9",
                "hashType": "type"
            }
        },
        "data": "0x00e1f505000000000000000000000000",
        "outPoint": {
            "txHash": "0xeec5c357338f622f9bf586532be687f8fc1918566f27b4abb7fa5f9c1891af6b",
            "index": "0x0"
        },
        "blockNumber": "0xcb42df",
        "txIndex": "0x2",
        "typeHash": "0x6d7dd4497d1ef095644e422d30b2456cfe32c6469346c77752a4d6b56f432a73"
    },
    .......
]
```

### PR DESCRIPTION
**Pull request by ShookLyngs**
## Changes
- Add basic validation to route params (e.g. txid, hash should be 64-character hex string)
- Write a custom `validatorCompiler` to promp only the first error if  `error instanceof ZodError`

## Related issues
- Fixes #210 

#### Route: `/rgbpp/v1/assets//`
```json
{
  "message": "Invalid btc_txid: should be a 64-character hex string"
}
```

#### Route `/rgbpp/v1/assets/63e7de3c59b7f28cfc1eb840c8d617b2f557770d2576355cfc0263e1925ac116/`
```json
{
  "message": "Invalid vout: cannot be empty"
}
```

#### Route: `/rgbpp/v1/assets/63e7de3c59b7f28cfc1eb840c8d617b2f557770d2576355cfc0263e1925ac116/-1`
```json
{
  "message": "Invalid vout: cannot be negative"
}
```

### CODE REVIEW

File: src/app.ts [hunk 1]
```diff
@@ -59,6 +60,23 @@ async function routes(fastify: FastifyInstance) {
   }
 }
 
+export const validatorCompiler: FastifySchemaCompiler<ZodAny> =
+  ({ schema }) =>
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  (data): any => {
+    try {
+      return { value: schema.parse(data) };
```
Comment (ahonn) [inline src/app.ts:68]: use [safeparse](https://zod.dev/?id=safeparse) instead of `parse` to avoid  try-catch

File: src/app.ts [hunk 2]
```diff
@@ -59,6 +60,23 @@ async function routes(fastify: FastifyInstance) {
...
+    } catch (error) {
+      if (error instanceof ZodError && error.errors.length) {
+        const firstError = error.errors[0];
+        return {
+          error: new Error(`Invalid ${firstError.path.join('.')}: ${error.errors[0].message}`),
```
Comment (ahonn) [inline src/app.ts:73]: prefer  throw `throw fastify.httpErrors.badRequest(error.message);` instead of default Error

File: src/app.ts (hunk 1 above)
Comment (ShookLyngs) [reply src/app.ts]: Updated at 56a7efd

File: src/app.ts (hunk 2 above)
Comment (ShookLyngs) [reply src/app.ts]: Updated at 56a7efd

**Review by Dawn-githup — APPROVED** [review]

**Comment by ShookLyngs** [comment]
@Flouse @Dawn-githup Fixed PR-related issues today:
- Should return `{ value: result.data }` in the validatorCompiler() method
- Should throw `HttpErrors.badRequest()` when the post rgbpp tx API params is invalid

**Comment by Dawn-githup** [comment]
### get balance
```
curl --location --request GET 'https://213.assets-api-342ddd42.nip.io/rgbpp/v1/address/tb1qwzawvkyywkfcvtz9wu8ly9yfs06vn00j5x44su/balance?type_script=%7B%20%20%22codeHash%22:%20%220x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb%22,%20%20%22hashType%22:%20%22type%22,%20%20%22args%22:%20%22%22%7D&no_cache=false' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJteS1hcHAiLCJhdWQiOiJhcGkudGVzdG5ldC5yZ2JwcC5pbyIsImp0aSI6IjBiOTE5NGJhLTE4NzItNGMyZS1iMzgwLTBjNDBkNzA2ZjNiZSIsImlhdCI6MTcyNDc1ODAxNX0.nhuE7hVQbVVcwQQ2naqQ5LEpESM9pdIlyQkwlkLJKEo' \
--header 'origin: https://api.testnet.rgbpp.io' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: 213.assets-api-342ddd42.nip.io' \
--header 'Connection: keep-alive'
```

error message:
```
{
    "message": "socket hang up"
}
```

### Description:

When attempting to call the get balance API, a socket hang up error occurred.

- Deployment Issue: This error did not occur in previous tests, suggesting that the deployment might have used a different RPC address, or there may have been changes to the RPC service configuration.

cc @Flouse @ShookLyngs

**Comment by Flouse** [comment]
> ## https://213.assets-api-342ddd42.nip.io/healthcheck

healthChecks are OK now.
cc @Dawn-githup @ShookLyngs

**Comment by Dawn-githup** [comment]
> > ## https://213.assets-api-342ddd42.nip.io/healthcheck
> 
> `healthChecks` are OK now. cc @Dawn-githup @ShookLyngs

- Integration test passed
https://app.apifox.com/link/project/4987016/api-test/test-report/6980363?branchId=4645721

**Review by Flouse — APPROVED** [review]
