### PR TITLE
fix: amount calculation in the rgbpp address balance endpoint

### LINKED ISSUE #202: Displaying incorrect balance when fetching RGB++ balance via BTC address
### Description

**Preconditions:**
- The total amount of 999 tokens is in the same UTXO.
- Leap 500 xudt.
- The BTC transaction is unconfirmed.
```jsx
Check: https://api.testnet.rgbpp.io/rgbpp/v1/address/tb1qt7gg5um02gj7yw0khdnsmzlqpqmcdz87zpvnh9/balance

{
  "address": "tb1qt7gg5um02gj7yw0khdnsmzlqpqmcdz87zpvnh9",
  "xudt": [
    {
      "name": "XUDT Test Token",
      "decimal": 8,
      "symbol": "FGG",
      "total_amount": "0xb9e459300",
      "available_amount": "0x0",
      "pending_amount": "0xb9e459300",
      "type_hash": "0xa5a802e130d41ed668d484e85ec6343ad58460f65fa319255e4fdad32ed5f64d",
      "type_script": {
        "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
        "args": "0x031933877ecd5ed36ea1db7d497d7d06a62ac1a68df3435c460357b319fe4e77",
        "hashType": "type"
      }
    }
  ]
}
```

**Issues:**
1. The `total_amount` should display as 999 but currently shows 499.
2. The `pending_amount` should display as 500 but currently shows 499.

### PR DESCRIPTION
**Pull request by ShookLyngs**
## Changes
- Fix #202 

## Fix details

The calculation in the `/rgbpp/address/{btc_address}/balance` endpoint has been refactored to:

- **Confirmed UTXOs:**
  1. Get all UTXOs
  2. Filter for all confirmed UTXOs
  3. Find the isomorphic XUDT cells corresponding to the UTXOs
  4. Add the amount of each target cell to the `total_amount` and `available_amount` fields

- **Unconfirmed UTXOs:**
  1. Get all UTXOs
  2. Filter for all unconfirmed UTXOs
  3. Find the isomorphic XUDT cells corresponding to the UTXOs
  4. Add the amount of each target cell to the `pending_amount` field

- **Unconfirmed Spent Outputs:**
  1. Get all transactions for the target BTC address
  5. Filter out all unconfirmed BTC transactions from the total transactions
  6. Find all RgbppLock XUDT cells in the inputs of the unconfirmed transactions
  7. Filter the above input cells to include only those belonging to the target BTC address
  8. Add the amount of each filtered cell to the `total_amount` field

### CODE REVIEW

**Comment by Dawn-githup** [comment]
Vercel deployed version access failed:

```
{"message":"Route GET:/ not found","error":"Not Found","statusCode":404}
```

File: src/routes/rgbpp/address.ts [hunk 1]
```diff
@@ -200,6 +218,49 @@ const addressRoutes: FastifyPluginCallback<Record<never, never>, Server, ZodType
         xudtBalances[type_hash].pending_amount = BI.from(xudtBalances[type_hash].pending_amount)
           .add(BI.from(amount))
           .toHexString();
+      });
+
+      // Find spent RgbppLock Xudt assets in unconfirmed transactions' inputs
+      const allTxs = await fastify.bitcoin.getAddressTxs({ address: btc_address });
```
Comment (Flouse) [inline src/routes/rgbpp/address.ts:224]: `GET /api/address/:address/txs` only returns up to 50 mempool transactions plus the first 25 confirmed transactions.

ref: https://mempool.space/docs/api/rest#get-address-transactions

**Comment by Flouse** [comment]
> **Unconfirmed Spent Outputs:**
> 
> 1. Get all transactions for the target BTC address
> 2. Filter out all unconfirmed BTC transactions from the total transactions
> 3. Find all RgbppLock XUDT cells in the inputs of the unconfirmed transactions
> 4. Filter the above input cells to include only those belonging to the target BTC address
> 5. Add the amount of each filtered cell to the `total_amount` field

Good catch!
This calculation is a necessary step in the [BTC --(leap)--> CKB] process.

File: src/routes/rgbpp/address.ts (hunk 1 above)
Comment (ShookLyngs) [reply src/routes/rgbpp/address.ts:224]: Okay, this is unexpected. Should I just fetch them page by page using this API until the response contains zero unconfirmed transactions? The other API doesn't seem fit for this feature, because it only returns the first 50 unconfirmed transactions without providing a pagination parameter: https://mempool.space/docs/api/rest#get-address-transactions-mempool

File: src/routes/rgbpp/address.ts [hunk 2]
```diff
@@ -200,6 +218,49 @@ const addressRoutes: FastifyPluginCallback<Record<never, never>, Server, ZodType
...
+          xudtBalances[type_hash] = {
+            ...xudtInfo,
+            type_hash,
+            total_amount: '0x0',
+            available_amount: '0x0',
+            pending_amount: '0x0',
+          };
+        }
+
         xudtBalances[type_hash].total_amount = BI.from(xudtBalances[type_hash].total_amount)
```
Comment (Flouse) [inline src/routes/rgbpp/address.ts:264]: ~~With this step, adding `Unconfirmed Spent Outputs`' xUDT value to total_amount,
the result of the described test in https://github.com/ckb-cell/btc-assets-api/issues/202#issue-2435982176 will be:
```js
  total_amount: '1399',
  available_amount: '0',
  pending_amount: '499',
```
Am I right?~~

No, I am wrong. See https://github.com/ckb-cell/btc-assets-api/blob/95fac7e5f9f7ddf2ed3d0c6b74693fda27732654/src/routes/rgbpp/address.ts#L206-L221
Pending balance is not calculated into total_amount.

File: src/routes/rgbpp/address.ts (hunk 1 above)
Comment (Flouse) [reply src/routes/rgbpp/address.ts:224]: An address with more than 50 pending BTC transactions is uncommon.
I think it is a rare case.

What about just explain this situation in the API description -> https://github.com/ckb-cell/btc-assets-api/blob/95fac7e5f9f7ddf2ed3d0c6b74693fda27732654/src/routes/rgbpp/address.ts#L128

e.g.
An address with more than 50 pending BTC transactions is uncommon. However, if such a situation arises, it potentially affecting the returned `total_amount`.

Comment (ShookLyngs) [reply src/routes/rgbpp/address.ts]: Updated description at 2119320f

**Comment by Dawn-githup** [comment]
curl -X 'GET' \
  'https://btc-assets-api-git-fix-202-unconfirmed-xudt-balance-cell-studio.vercel.app/rgbpp/v1/address/tb1qlmafss8vm2v82700j9ztzqp07nfqy6wwhazv9q/balance?type_script=%7B%0A%20%20%22codeHash%22%3A%20%220x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb%22%2C%0A%20%20%22hashType%22%3A%20%22type%22%2C%0A%20%20%22args%22%3A%20%22%22%0A%7D&no_cache=false' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJteS1hcHAiLCJhdWQiOiJidGMtYXNzZXRzLWFwaS1naXQtZml4LTIwMi11bmNvbmZpcm1lZC14dWR0LWJhbGFuY2UtY2VsbC1zdHVkaW8udmVyY2VsLmFwcCIsImp0aSI6IjIyMWY0MGU5LWQ3ZTQtNGM4YS05YzgyLWUyZDg5OGJhYjc0OSIsImlhdCI6MTcyNDA4MzU1M30.xSMoL0r9BEuqlj9dCv4SwtCMmMi5QF05H_o7ioxKT-o'

```
{
    "message": "ERR max request size exceeded. Limit: 1048576 bytes, Actual: 6064477 bytes. See https://upstash.com/docs/redis/troubleshooting/max_request_size_exceeded for details"
}
```

**Comment by ShookLyngs** [comment]
@Flouse @ahonn Another issue that affects the balance calculation is that, currently, if a job in the queue has been retried a certain number of times, it will be marked as `failed`. In the `getPendingInputCellsByTxid()` and `getPendingOutputCellsByTxid()` methods, if the target job is marked as `failed`, an empty list `[]` will be returned.

This means that if we're transferring some RGBPP assets and the BTC_TX gets stuck for a while, the job in the queue will be marked as `failed` and excluded from the balance calculation. We have roughly two ways to handle this issue:
1. **It's expected:** Failed jobs should be reactivated manually to be included in the balance calculation
2. **It's unexpected:** Failed jobs should be included in the balance calculation

If this is unexpected behavior, a possible resolution is to add a `allowFailedJob: boolean = false` parameter to the `getPendingInputCellsByTxid` and `getPendingOutputCellsByTxid` methods, allowing them to retrieve the input/output cells from the failed jobs.

Ref: https://github.com/ckb-cell/btc-assets-api/pull/206/files#diff-c69299e8c418dcefed9c4114412c428323e0060b87a31d3e8c6b3d5b92db8057R628-R632

**Comment by Flouse** [comment]
> Another issue that affects the balance calculation is that, currently, if a job in the queue has been retried a certain number of times, it will be marked as `failed`. In the `getPendingInputCellsByTxid()` and `getPendingOutputCellsByTxid()` methods, if the target job is marked as `failed`, an empty list `[]` will be returned.
> 
> This means that if we're transferring some RGBPP assets and the BTC_TX gets stuck for a while, the job in the queue will be marked as `failed` and excluded from the balance calculation. We have roughly two ways to handle this issue:
> 
> 1. **It's expected:** Failed jobs should be reactivated manually to be included in the balance calculation
> 2. **It's unexpected:** Failed jobs should be included in the balance calculation
> 
> If this is unexpected behavior, a possible resolution is to add a `allowFailedJob: boolean = false` parameter to the `getPendingInputCellsByTxid` and `getPendingOutputCellsByTxid` methods, allowing them to retrieve the input/output cells from the failed jobs.
> 
> Ref: https://github.com/ckb-cell/btc-assets-api/pull/206/files#diff-c69299e8c418dcefed9c4114412c428323e0060b87a31d3e8c6b3d5b92db8057R628-R632

https://github.com/ckb-cell/btc-assets-api/issues/207 is created including the proposed resolutions. Let's discuss it and handle it later.

**Comment by ahonn** [comment]
The reason why Unit Tests failed may be that redis flushall has not been executed yet, but the test has begun to be executed.
The test of mempool/elelctrs uses the same redis, so it may be affected.

Please try:
```
beforeAll(async () => {
  await container.cradle.redis.flushall();
});
```

**Comment by ShookLyngs** [comment]
@flouse @ahonn Test-related fixes have been reverted since the error appears randomly in the test workflow but not in the local environment. We can skip the error and merge it.

**Review by Flouse — APPROVED** [review]
